services:
  questdb:
    image: questdb/questdb:latest
    container_name: questdb
    ports:
      - "9000:9000"
      - "8812:8812"
      - "9009:9009"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-init:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - >
        echo "Waiting for Kafka..." &&
        cub kafka-ready -b kafka:29092 1 40 &&
        echo "Creating topics..." &&
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic ticks.v1 --replication-factor 1 --partitions 8 &&
        kafka-topics --bootstrap-server kafka:29092 --alter --topic ticks.v1 --partitions 8 || true &&
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic candles.v1 --replication-factor 1 --partitions 8 &&
        kafka-topics --bootstrap-server kafka:29092 --alter --topic candles.v1 --partitions 8 || true &&
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic ticks.dlq.v1 --replication-factor 1 --partitions 1 &&
        echo "Kafka topic setup complete."
    restart: "no"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: [ "--config=/etc/otelcol/config.yaml" ]
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4318:4318"   # OTLP HTTP in
      - "9464:9464"   # Prometheus scrape out

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on: [ otel-collector ]
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on: [ prometheus ]
    ports:
      - "3000:3000"